### PR TITLE
[MRG] Documentation: added sphinx support and some first docstrings

### PR DESCRIPTION
**Pull request by NicolasHug**
This PR adds a `doc` directory, setups sphinx (separate `build` and `source` directories) with `sphinx-quickstart` and adds some first docstring proposals for the estimators.

Should we set up something on ReadTheDocs or equivalent?

I set up the RTD theme because I like it but I'm open to anything of course.

### CODE REVIEW

**Comment by ogrisel** [comment]
I am fine with readthedoc.

**Comment by ogrisel** [comment]
I think it's fine just to build a "dev" version of the doc from the master and a "stable" version of the doc from the stable release when we make one.

**Comment by NicolasHug** [comment]
Ok.

Then I'm not sure what you mean by *once it's easy to read the doc online*

**Comment by NicolasHug** [comment]
Merged @ogrisel , the docs are here: https://pygbm.readthedocs.io/en/latest/
and the repo RTD project here: https://readthedocs.org/projects/pygbm/

I flattened everything in `index.rst` but that's just to see what it looks like.

As I don't have admin rights on the github repo, RTD couldn't set up the hooks so new commits won't trigger the doc buildings. I added you as admin on RTD maybe that will fix it.

**Pull request merged**
