### PR TITLE
[WIP] Do not store histogram on SplitInfo

### PR DESCRIPTION
**Pull request by ogrisel**
Tentative fix for #31.

### CODE REVIEW

**Comment by ogrisel** [comment]
At this time some tests are broken (need to be updated) and the code runs slightly slower than on master for some reason I do not understand yet.

The memory leak issue should be fixed though.

**Comment by ogrisel** [comment]
The fact that we observe a slowdown when we update the packed `histograms` array in the parallel for loop while we do not observe this issue in master where the packed histograms array is filled sequentially might be a case of [False Sharing](https://en.wikipedia.org/wiki/False_sharing).

**Comment by ogrisel** [comment]
Actually I tried again with master and the various threading backends and this PR is either as fast or faster than master. I must have done something wrong when I reported the initial slow down.

In any case, tbb is significantly faster than the workqueue backend when the number of cores is large (e.g. 12 in my case).

**Comment by ogrisel** [comment]
@NicolasHug I have to go, feel free to update the failing tests and merge this PR.

**Comment by ogrisel** [comment]
Cool, let's merge as it's already a net improvement.

About the minimal reproduction case, I confirm I get the leak with your code, without any error message or exception. Just memory usage increasing as reported by psutil.

**Comment by ogrisel** [comment]
We still have a discrepancy in terms of results with LightGBM though. But there is another issue for that.

**Comment by NicolasHug** [comment]
I have opened https://github.com/numba/numba/issues/3473 and https://github.com/numba/numba/issues/3472 regarding the leak and some other weird stuff I found.

**Pull request merged**
